# Generated by Django 5.0.7 on 2024-08-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='mode',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
    ]
