# Generated by Django 5.0.7 on 2024-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt_token',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
